apiVersion: v1
name: fitness-center-weekly
description: fitness center weekly mailer
type: application
version: 0.1.15
appVersion: 1.8.5
icon: file://../logo.png
keywords:
  - buildinglink
  - aware
  - iot
  - solutions
maintainers:
  - name: buildinglink  
    email: charts@buildinglink.com

