apiVersion: v1
name: digest-q-gen
description: Buildinglink priority email service
type: application
version: 0.1.3
appVersion: 1.0.0
icon: file://../logo.png
keywords:
  - buildinglink
  - mailers
maintainers:
  - name: buildinglink  
    email: charts@buildinglink.com
